// Localization
const translations = {
    "en": {
        // Index.html translations
        "toggleDarkMode": "Toggle Dark Mode",
        "toggleLightMode": "Toggle Light Mode",
        "english": "English",
        "nepali": "Nepali",
        // To-Do List
        "todoList": "To-Do List",
        "addTask": "Add Task",
        "taskName": "Task Name",
        "priority": "Priority",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "dueDate": "Due Date",
        "category": "Category",
        "general": "General",
        "work": "Work",
        "personal": "Personal",
        "all": "All",
        "filterByCategory": "Filter by Category",
        "noTasks": "No tasks found.",
        "completed": "Completed",
        "actions": "Actions",
        "noDueDate": "No due date",
        "showNotes": "Show Notes",
        "taskDueToday": "Task Due Today",
        "taskDueReminder": "Reminder: Task \"{task}\" is due today!",
        "notes": "Notes",
        "sendEmail": "Send Email",
        "emailPlaceholder": "Enter recipient email",
        "emailInvalid": "Please enter a valid email address",
        "deleteAllConfirm": "Are you sure you want to delete all tasks?",
        "noTasksToExport": "No tasks to export.",
        "noTasksToSend": "No tasks to send.",
        "undo": "Undo",
        "redo": "Redo",
        "noUndo": "No actions to undo.",
        "noRedo": "No actions to redo.",
        "backup": "Backup",
        "restore": "Restore",
        "loadTasksError": "Unable to load tasks: {error}",
        "saveTasksError": "Unable to save tasks: {error}",
        "addTaskError": "Failed to add task: {error}",
        "markCompletedError": "Failed to mark task completed: {error}",
        "deleteTaskError": "Failed to delete task: {error}",
        "markAllCompletedError": "Failed to mark all tasks completed: {error}",
        "deleteAllTasksError": "Failed to delete all tasks: {error}",
        "undoError": "Failed to undo: {error}",
        "redoError": "Failed to redo: {error}",
        "sortTasksError": "Failed to sort tasks: {error}",
        "exportExcelError": "Failed to export to Excel: {error}",
        "backupError": "Failed to backup data: {error}",
        "restoreError": "Failed to restore data: {error}",
        "invalidBackupFormat": "Invalid backup format: must be an array.",
        "noValidTasks": "No valid tasks found in backup.",
        "restoreSuccess": "Data restored successfully! {processed} tasks processed, {added} new tasks added.",
        "readFileError": "Failed to read file: {error}",
        // Spending Tracker
        "spendingTracker": "Spending Tracker",
        "addEntry": "Add Entry",
        "addSpendingEntryHeader": "Add Spending Entry",
        "addIncome": "Add Income",
        "addExpense": "Add Expense",
        "summaryReport": "Summary Report",
        "exportExcel": "Export to Excel",
        "exportPDF": "Export to PDF",
        "amount": "Amount",
        "type": "Type",
        "income": "Income",
        "expense": "Expense",
        "date": "Date",
        "recurrence": "Recurrence",
        "none": "None",
        "daily": "Daily",
        "weekly": "Weekly",
        "monthly": "Monthly",
        "currency": "Currency",
        "viewSummary": "View Summary",
        "manageEntries": "Manage Entries",
        "setBudget": "Set Budget",
        "manageCategories": "Manage Categories",
        "manageEntriesTitle": "Manage Spending Entries",
        "searchPlaceholder": "Search...",
        "filterByType": "Filter by Type",
        "filterByCategory": "Filter by Category",
        "dateRange": "Date Range",
        "startDate": "Start Date",
        "endDate": "End Date",
        "editSpendingEntry": "Edit Spending Entry",
        "stopRecurrence": "Stop Recurrence",
        "budgetTitle": "Set Monthly Budget",
        "budgetOptional": "Budget setting is optional. Click 'Save' to set budgets, or 'Cancel' to skip.",
        "budgetFor": "Budget for",
        "budgetExceeded": "Budget exceeded for {category}! Spent: {spent}, Budget: {budget}",
        "noBudgetSet": "No budgets set.",
        "weeklySummary": "Weekly Summary (Current Week, Monday to Sunday)",
        "day": "Day",
        "incomeLabel": "Income",
        "expenses": "Expenses",
        "balance": "Balance",
        "monthlySummary": "Monthly Summary",
        "yearlySummary": "Yearly Summary",
        "totalIncome": "Total Income",
        "totalExpenses": "Total Expenses",
        "netBalance": "Net Balance",
        "categoryWiseExpenses": "Category-wise Expenses",
        "monthlyTrends": "Monthly Trends (Last 6 Months)",
        "newCategory": "New Category",
        "categoryName": "Category Name",
        "addCategory": "Add Category",
        // Shopping List
        "shoppingList": "Shopping List",
        "addItem": "Add Item",
        "itemName": "Item Name",
        "quantity": "Quantity",
        "status": "Status",
        "purchased": "Purchased",
        "notPurchased": "Not Purchased",
        "filterByStatus": "Filter by Status",
        // New translations for Add Purchase Expense modal
        "addPurchaseExpense": "Add Purchase Expense",
        "enterAmountSpent": "Enter the amount spent on {item} ({quantity} unit(s)).",
        // Notifications
        "enableNotifications": "Enable Notifications",
        "notificationsEnabled": "Notifications are already enabled.",
        "notificationsDenied": "Notification permission was denied. Please enable it in your browser settings.",
        // Shared Categories
        "food": "Food",
        "rent": "Rent",
        "salary": "Salary",
        "utilities": "Utilities",
        "entertainment": "Entertainment",
        "other": "Other",
        // Shared UI Elements
        "noEntries": "No entries found.",
        "edit": "Edit",
        "delete": "Delete",
        "cancel": "Cancel",
        "save": "Save",
        "close": "Close",
        "deleteCategoryConfirm": "Are you sure you want to delete this item?"
    },
    "ne": {
        "toggleDarkMode": "डार्क मोड टगल गर्नुहोस्",
        "toggleLightMode": "लाइट मोड टगल गर्नुहोस्",
        "english": "अंग्रेजी",
        "nepali": "नेपाली",
        "todoList": "कार्य सूची",
        "addTask": "कार्य थप्नुहोस्",
        "taskName": "कार्यको नाम",
        "priority": "प्राथमिकता",
        "low": "कम",
        "medium": "मध्यम",
        "high": "उच्च",
        "dueDate": "अन्तिम मिति",
        "category": "श्रेणी",
        "general": "सामान्य",
        "work": "काम",
        "personal": "व्यक्तिगत",
        "all": "सबै",
        "filterByCategory": "श्रेणी अनुसार फिल्टर गर्नुहोस्",
        "noTasks": "कुनै कार्यहरू फेला परेन।",
        "completed": "पुरा भएको",
        "actions": "कार्यहरू",
        "noDueDate": "कुनै अन्तिम मिति छैन",
        "showNotes": "नोटहरू देखाउनुहोस्",
        "taskDueToday": "आजको कार्य बाँकी",
        "taskDueReminder": "रिमाइन्डर: कार्य \"{task}\" आज बाँकी छ!",
        "notes": "नोटहरू",
        "sendEmail": "इमेल पठाउनुहोस्",
        "emailPlaceholder": "प्रापकको इमेल प्रविष्ट गर्नुहोस्",
        "emailInvalid": "कृपया मान्य इमेल ठेगाना प्रविष्ट गर्नुहोस्",
        "deleteAllConfirm": "के तपाईं सबै कार्यहरू हटाउन निश्चित हुनुहुन्छ?",
        "noTasksToExport": "निर्यात गर्न कुनै कार्यहरू छैनन्।",
        "noTasksToSend": "पठाउन कुनै कार्यहरू छैनन्।",
        "undo": "रद्द गर्नुहोस्",
        "redo": "पुनः गर्नुहोस्",
        "noUndo": "रद्द गर्न कुनै कार्यहरू छैनन्।",
        "noRedo": "पुनः गर्न कुनै कार्यहरू छैनन्।",
        "backup": "ब्याकअप",
        "restore": "पुनर्स्थापना",
        "loadTasksError": "कार्यहरू लोड गर्न असमर्थ: {error}",
        "saveTasksError": "कार्यहरू बचत गर्न असमर्थ: {error}",
        "addTaskError": "कार्य थप्न असफल: {error}",
        "markCompletedError": "कार्य पूरा भएको चिन्ह लगाउन असफल: {error}",
        "deleteTaskError": "कार्य हटाउन असफल: {error}",
        "markAllCompletedError": "सबै कार्यहरू पूरा भएको चिन्ह लगाउन असफल: {error}",
        "deleteAllTasksError": "सबै कार्यहरू हटाउन असफल: {error}",
        "undoError": "रद्द गर्न असफल: {error}",
        "redoError": "पुनः गर्न असफल: {error}",
        "sortTasksError": "कार्यहरू क्रमबद्ध गर्न असफल: {error}",
        "exportExcelError": "एक्सेलमा निर्यात गर्न असफल: {error}",
        "backupError": "डाटा ब्याकअप गर्न असफल: {error}",
        "restoreError": "डाटा पुनर्स्थापना गर्न असफल: {error}",
        "invalidBackupFormat": "अमान्य ब्याकअप ढाँचा: यो एक एर्रे हुनुपर्छ।",
        "noValidTasks": "ब्याकअपमा कुनै मान्य कार्यहरू फेला परेन।",
        "restoreSuccess": "डाटा सफलतापूर्वक पुनर्स्थापना गरियो! {processed} कार्यहरू प्रशोधन गरियो, {added} नयाँ कार्यहरू थपियो।",
        "readFileError": "फाइल पढ्न असफल: {error}",
        "spendingTracker": "खर्च ट्र्याकर",
        "addEntry": "प्रविष्टि थप्नुहोस्",
        "addSpendingEntryHeader": "खर्च प्रविष्टि थप्नुहोस्",
        "addIncome": "आय थप्नुहोस्",
        "addExpense": "खर्च थप्नुहोस्",
        "summaryReport": "सारांश प्रतिवेदन",
        "exportExcel": "एक्सेलमा निर्यात गर्नुहोस्",
        "exportPDF": "PDF मा निर्यात गर्नुहोस्",
        "amount": "रकम",
        "type": "प्रकार",
        "income": "आय",
        "expense": "खर्च",
        "date": "मिति",
        "recurrence": "पुनरावृत्ति",
        "none": "कुनै पनि होइन",
        "daily": "दैनिक",
        "weekly": "साप्ताहिक",
        "monthly": "मासिक",
        "currency": "मुद्रा",
        "viewSummary": "सारांश हेर्नुहोस्",
        "manageEntries": "प्रविष्टिहरू व्यवस्थापन गर्नुहोस्",
        "setBudget": "बजेट सेट गर्नुहोस्",
        "manageCategories": "श्रेणीहरू व्यवस्थापन गर्नुहोस्",
        "manageEntriesTitle": "खर्च प्रविष्टिहरू व्यवस्थापन गर्नुहोस्",
        "searchPlaceholder": "खोज्नुहोस्...",
        "filterByType": "प्रकार अनुसार फिल्टर गर्नुहोस्",
        "filterByCategory": "श्रेणी अनुसार फिल्टर गर्नुहोस्",
        "dateRange": "मिति दायरा",
        "startDate": "सुरु मिति",
        "endDate": "अन्त्य मिति",
        "editSpendingEntry": "खर्च प्रविष्टि सम्पादन गर्नुहोस्",
        "stopRecurrence": "पुनरावृत्ति रोक्नुहोस्",
        "budgetTitle": "मासिक बजेट सेट गर्नुहोस्",
        "budgetOptional": "बजेट सेटिङ वैकल्पिक छ। बजेट सेट गर्न 'सुरक्षित गर्नुहोस्' मा क्लिक गर्नुहोस्, वा 'रद्द गर्नुहोस्' मा क्लिक गर्नुहोस्।",
        "budgetFor": "को लागि बजेट",
        "budgetExceeded": "{category} को लागि बजेट नाघ्यो! खर्च: {spent}, बजेट: {budget}",
        "noBudgetSet": "कुनै बजेट सेट गरिएको छैन।",
        "weeklySummary": "साप्ताहिक सारांश (हालको हप्ता, सोमबार देखि आइतबार)",
        "day": "दिन",
        "incomeLabel": "आय",
        "expenses": "खर्चहरू",
        "balance": "सन्तुलन",
        "monthlySummary": "मासिक सारांश",
        "yearlySummary": "वार्षिक सारांश",
        "totalIncome": "कुल आय",
        "totalExpenses": "कुल खर्च",
        "netBalance": "शुद्ध सन्तुलन",
        "categoryWiseExpenses": "श्रेणीगत खर्चहरू",
        "monthlyTrends": "मासिक प्रवृत्तिहरू (पछिल्लो ६ महिना)",
        "newCategory": "नयाँ श्रेणी",
        "categoryName": "श्रेणीको नाम",
        "addCategory": "श्रेणी थप्नुहोस्",
        "shoppingList": "किनमेल सूची",
        "addItem": "वस्तु थप्नुहोस्",
        "itemName": "वस्तुको नाम",
        "quantity": "परिमाण",
        "status": "स्थिति",
        "purchased": "खरिद गरिएको",
        "notPurchased": "खरिद नगरिएको",
        "filterByStatus": "स्थिति अनुसार फिल्टर गर्नुहोस्",
        "addPurchaseExpense": "खरिद खर्च थप्नुहोस्",
        "enterAmountSpent": "{item} मा खर्च गरिएको रकम प्रविष्ट गर्नुहोस् ({quantity} एकाइ(हरू))।",
        "enableNotifications": "सूचनाहरू सक्षम गर्नुहोस्",
        "notificationsEnabled": "सूचनाहरू पहिले नै सक्षम छन्।",
        "notificationsDenied": "सूचना अनुमति अस्वीकार गरिएको छ। कृपया आफ्नो ब्राउजर सेटिङहरूमा सक्षम गर्नुहोस्।",
        "food": "खाना",
        "rent": "भाडा",
        "salary": "तलब",
        "utilities": "उपयोगिताहरू",
        "entertainment": "मनोरञ्जन",
        "other": "अन्य",
        "noEntries": "कुनै प्रविष्टिहरू फेला परेन।",
        "edit": "सम्पादन गर्नुहोस्",
        "delete": "हटाउनुहोस्",
        "cancel": "रद्द गर्नुहोस्",
        "save": "सुरक्षित गर्नुहोस्",
        "close": "बन्द गर्नुहोस्",
        "deleteCategoryConfirm": "के तपाईं यो वस्तु हटाउन निश्चित हुनुहुन्छ?"
    }
};
